### PR TITLE
[WIP] lstm example, need help

### PR DESCRIPTION
**Pull request by thirdwing**
I am working on a lstm example in C++. I must have done something wrong since I got the following errors in `rnn_sym.InferArgsMap(Context::cpu(), &args_map, args_map);`. It seems from the line `Symbol wordvec = SliceChannel("wordvec", embed, seq_len);`.

Maybe my understanding is wrong.

Can you give me some suggestions? @tqchen @hjk41 

```
[12:22:08] src/operator/./slice_channel-inl.h:150: Check failed: (dshape[param_.axis] % param_.num_outputs) == (0) num_outputs (129) does not divide input dimension 1 (1).
[12:22:08] include/mxnet-cpp/symbol.hpp:178: Check failed: (MXSymbolInferShape(GetHandle(), keys.size(), keys.data(), arg_ind_ptr.data(), arg_shape_data.data(), &in_shape_size, &in_shape_ndim, &in_shape_data, &out_shape_size, &out_shape_ndim, &out_shape_data, &aux_shape_size, &aux_shape_ndim, &aux_shape_data, &complete)) == ( 0) 
```

### CODE REVIEW

**Comment by hjk41** [comment]
There are two declarations of SliceChannel, one in op.h, the other in op_suppl.h. I think the one in op.h, which is the one you are using, is ill-defined. I will correct it.

In the meanwhile, you can use the other version of SliceChannel:

``` c++
/*!
 * \breif Slice input equally along specified axis.
 * \param data input symbol. 
 * \param num_outputs Number of outputs to be sliced. 
 * \param axis Dimension along which to slice. 
 * \param squeeze_axis If true AND the sliced dimension becomes 1, squeeze that dimension. 
 * \return new symbol
 */
inline Symbol SliceChannel(Symbol data,
                           int num_outputs,
                           int axis = 1,
bool squeeze_axis = false)
```

**Comment by thirdwing** [comment]
I think I have already used the one in `op_suppl.h`. The one in `op.h` doesn't have the parameter `data`.

**Comment by hjk41** [comment]
This is wierd. The version in op_suppl.h does not have the symbol name parameter. I don't see why your program can compile...

**Comment by zhangchen-qinyinghua** [comment]
There seems to be mistake in data shape.
https://github.com/dmlc/MXNet.cpp/pull/43/files#diff-86b105ea61bd4e8646baae5797117113R132
The second dimension (dim_1) should be divided by slice channel counts.
The following code seems work:
`args_map["data"] = NDArray(Shape(batch_size, seq_len), Context::cpu());`

**Comment by thirdwing** [comment]
@zhangchen-qinyinghua 

This fixed the error, however, `args_map` only has `data` and `data_label` after `rnn_sym.InferArgsMap(Context::cpu(), &args_map, args_map);`

There is still something wrong. I will check the network definition.

**Comment by thirdwing** [comment]
I found my mistake, I will update this soon.

**Pull request closed without merging**
