### PR TITLE
shape.h uses streams and c_api.h uses size_t but these were not included

### PR DESCRIPTION
**Pull request by kotaweav**
The assumption seemed to be that #include <iostream> was called before
 #include "MxNetCpp.h" but it shouldn't be required to have that
 ordering or include iostream at all.

### CODE REVIEW

**Comment by zhangchen-qinyinghua** [comment]
Is it necessary to change the c_api.h?
We'd better make it consistent with what it is inside the mxnet.

**Comment by kotaweav** [comment]
Sure, we can make those changes elsewhere. I think it works to put them in MxNetCpp.h.

**Comment by kotaweav** [comment]
Ugh... I really shouldn't be doing these things when I'm so tired... My apologies for all the excess mistake commits... Should have cleaned things up before pushing...

**Comment by kotaweav** [comment]
Okay, so the changes are no longer in c_api.h, and I also merged back the upstream changes into this. Should be all set now.

**Pull request merged**
