### PR TITLE
Make include structure more friendly for system-wide installs

### PR DESCRIPTION
**Pull request by kotaweav**
By putting the header files in their own folder and updating the include
preprocessor directives appropriately, system-wide installs are better
isolated. In addition, names like "base.h" and "logger.h" are pretty
common in larger systems, and thus, by putting these in a separate
mxnet/ folder, conflicts can be avoided.

### CODE REVIEW

**Comment by zhangchen-qinyinghua** [comment]
Yeah, you're right.
However, let us just make the directory name "mxnet.cpp" rather than "mxnet".

**Comment by kotaweav** [comment]
How about "mxnet-cpp"? i'm a little reluctant to put a "." in the directory name, and a dash is pretty common.

**Comment by zhangchen-qinyinghua** [comment]
Is it necessary to change the c_api.h?
We'd better make it consistent with what it is inside the mxnet.

**Comment by zhangchen-qinyinghua** [comment]
I think mxnet-cpp is fine.

**Comment by kotaweav** [comment]
Alright, made the change.

**Pull request merged**
