### PR TITLE
Report exception details, default grad_req to kNullOp for label

### PR DESCRIPTION
**Pull request by mz24cn**
1, logging.h revised: Facilitate to debug. otherwise the exception cannot be captured, details
cannot be acquired, the program directly crashed.
2, initializer.h revised: https://github.com/dmlc/mxnet/pull/4819

### CODE REVIEW

**Comment by conopt** [comment]
Hi, do you mind to seperate this pr into two parts? 1) minor fixes: assertion detail report and default grad_req for label 2) initializer revise.

**Comment by conopt** [comment]
It seems the parameter initialization revise is related to mxnet.

**Comment by craftit** [comment]
It is better if the program at least optionally aborts on an error rather than exits, as you can get a core dump, use a debug tool.  It also saves on time setting up a break point directly.   Ideally you would give the programmer the a callback so if it is being part of a user interface the program can just report the error to the user and continue.

**Comment by mz24cn** [comment]
@craftit okay since some programer like abort(). What you said is true that abort is useful as debug hook. I change it to exit() only because when I revise the network structure, abort() pops up app crash messagebox again and again is really annoying. Since error details now are reported, I need not replace abort().
@lx75249 I will separate to two PR. https://github.com/dmlc/mxnet/pull/4644 moved the files that dmlc/mxnet#4819 modified, leaing to conflicts. https://github.com/dmlc/mxnet/pull/4644 effect is waiting for benchmark: https://github.com/hclhkbu/dlbench/issues/5 (my test results: https://github.com/dmlc/mxnet/issues/4878)

**Comment by mz24cn** [comment]
another initializer revise should be waited you after merging this PR, right? @lx75249

**Pull request merged**
